/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import algorithm.BackPropagation;
import algorithm.Camada;
import algorithm.Neuronio;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author bruno
 */
public class IUAlterarPesos extends javax.swing.JDialog {

    public BackPropagation rede;
    public HashMap<Integer, Double> hash;
    
    /**
     * Creates new form IUAlterarPesos
     */
    public IUAlterarPesos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {    
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
        this.setTitle("Alterar pesos");
        
        hash = new HashMap<>();
        
        //this.tfAlterarPeso.setText(this.ComboBoxPesos.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCamadas = new javax.swing.JComboBox<>();
        ComboBoxPesos = new javax.swing.JComboBox<>();
        tfAlterarPeso = new javax.swing.JTextField();
        btnSalvarPesos = new javax.swing.JButton();
        ComboBoxNeuronios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfJ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Camadas:");

        jLabel2.setText("Pesos W(i,j):");

        jLabel3.setText("Alterar peso:");

        ComboBoxCamadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oculta", "Saída" }));
        ComboBoxCamadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCamadasActionPerformed(evt);
            }
        });

        ComboBoxPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPesosActionPerformed(evt);
            }
        });

        tfAlterarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlterarPesoActionPerformed(evt);
            }
        });

        btnSalvarPesos.setText("Salvar alteração");
        btnSalvarPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPesosActionPerformed(evt);
            }
        });

        ComboBoxNeuronios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNeuroniosActionPerformed(evt);
            }
        });

        jLabel4.setText("Neurônios:");

        jLabel5.setText("W");

        jLabel6.setText("i");

        tfJ.setEnabled(false);

        jLabel7.setText("j");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarPesos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(tfAlterarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxNeuronios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ComboBoxCamadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ComboBoxPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfJ, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxNeuronios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(ComboBoxPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlterarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarPesos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlterarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlterarPesoActionPerformed
        // TODO add your handling code here:
        
        //this.tfAlterarPeso.setText(this.ComboBoxPesos.getSelectedItem().toString());
        
    }//GEN-LAST:event_tfAlterarPesoActionPerformed

    private void ComboBoxPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPesosActionPerformed
        // TODO add your handling code here:
        
       
        try{
            Double peso = hash.get(Integer.parseInt(this.ComboBoxPesos.getSelectedItem().toString()));
            this.tfAlterarPeso.setText(String.valueOf(peso));
        }catch(NullPointerException e){
            //Erro
        }
                
    }//GEN-LAST:event_ComboBoxPesosActionPerformed

    private void ComboBoxCamadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCamadasActionPerformed
        // TODO add your handling code here:
        
        if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Oculta")){
            
            this.ComboBoxNeuronios.removeAllItems();
            this.ComboBoxPesos.removeAllItems();
            this.tfJ.setText("");
            for(Neuronio n : rede.getCamada(Camada.OCULTA).getNeuronios()){
                this.ComboBoxNeuronios.addItem(String.valueOf(n.getId()));
            }
        }
        else if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Saída")){
            
            this.ComboBoxNeuronios.removeAllItems();
            this.ComboBoxPesos.removeAllItems();
            this.tfJ.setText("");
            for(Neuronio n : rede.getCamada(Camada.SAIDA).getNeuronios()){
                this.ComboBoxNeuronios.addItem(String.valueOf(n.getId()));
            }
        }
        
    }//GEN-LAST:event_ComboBoxCamadasActionPerformed

    private void ComboBoxNeuroniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNeuroniosActionPerformed
        // TODO add your handling code here:
        try{
            
            if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Oculta")){
            
                int idNeuronio = Integer.parseInt(this.ComboBoxNeuronios.getSelectedItem().toString());
                Neuronio n = rede.getCamada(Camada.OCULTA).getNeuronio(idNeuronio);
                hash = n.getPesos();

                this.ComboBoxPesos.removeAllItems();
                for(Integer i : hash.keySet()){
                    this.ComboBoxPesos.addItem(String.valueOf(i));
                }

            }
            else if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Saída")){

                int idNeuronio = Integer.parseInt(this.ComboBoxNeuronios.getSelectedItem().toString());
                Neuronio n = rede.getCamada(Camada.SAIDA).getNeuronio(idNeuronio);
                hash = n.getPesos();

                this.ComboBoxPesos.removeAllItems();
                for(Integer i : hash.keySet()){
                    this.ComboBoxPesos.addItem(String.valueOf(i));
                }
            }

            this.tfJ.setText(this.ComboBoxNeuronios.getSelectedItem().toString());
            
        }catch(NullPointerException e){
            //Erro
        }
        
        
    }//GEN-LAST:event_ComboBoxNeuroniosActionPerformed

    private void btnSalvarPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPesosActionPerformed
        // TODO add your handling code here:
        
        if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Oculta")){
            
            int neuronio = Integer.parseInt(this.ComboBoxNeuronios.getSelectedItem().toString());
            int numPeso = Integer.parseInt(this.ComboBoxPesos.getSelectedItem().toString());
            double novoPeso = Double.parseDouble(this.tfAlterarPeso.getText());
            
            rede.getCamada(Camada.OCULTA).getNeuronio(neuronio).setPeso(numPeso, novoPeso);
        }
        else if(this.ComboBoxCamadas.getSelectedItem().toString().equals("Saída")){
            
            int neuronio = Integer.parseInt(this.ComboBoxNeuronios.getSelectedItem().toString());
            int numPeso = Integer.parseInt(this.ComboBoxPesos.getSelectedItem().toString());
            double novoPeso = Double.parseDouble(this.tfAlterarPeso.getText());
            
            rede.getCamada(Camada.SAIDA).getNeuronio(neuronio).setPeso(numPeso, novoPeso);
        }
        
        JOptionPane.showMessageDialog(null, "Peso alterado com sucesso!");

        
    }//GEN-LAST:event_btnSalvarPesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUAlterarPesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUAlterarPesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUAlterarPesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUAlterarPesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUAlterarPesos dialog = new IUAlterarPesos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCamadas;
    private javax.swing.JComboBox<String> ComboBoxNeuronios;
    private javax.swing.JComboBox<String> ComboBoxPesos;
    private javax.swing.JButton btnSalvarPesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfAlterarPeso;
    private javax.swing.JTextField tfJ;
    // End of variables declaration//GEN-END:variables
}
